### ISSUE TITLE
Installation Guide no longer available...

### ISSUE THREAD

**Issue by huggi77** [ibuetler/e1pub#24]
https://github.com/ibuetler/e1pub/tree/master/hacking-lab-livecd-installation gives a 404-error.

**Comment by ibuetler** [comment]
where did you find this URL?
the new URL is https://github.com/Hacking-Lab/hl-livecd/

**Comment by huggi77** [comment]
Sorry, I was feeling "nostalgic": Step 1:
https://www.hacking-lab.com/Remote_Sec_Lab/ 

Thanks for the updated link anyway.

**Comment by ibuetler** [comment]
Will not update the https://www.hacking-lab.com/Remote_Sec_Lab/ , as this page will go offline in 10 days
HL1.0 is end of life
Ivan
