### ISSUE TITLE
Importing OVA file failure

### ISSUE THREAD

**Issue by rockmeup** [ibuetler/e1pub#3]
The import failed because /root/Downloads/hl-livecd.ova did not pass OVF specification conformance or virtual hardware compliance checks.

Click Retry to relax OVF specification and virtual hardware compliance checks and try the import again, or click Cancel to cancel the import. If you retry the import, you might not be able to use the virtual machine in VMware Workstation.

**Comment by ibuetler** [comment]
Vmware Issue. You must accept twice. This is weird; even if we export the OVA from Vmware, the import is still complaining about not passing OVF specs. But if you click RETRY, it works like charm. 

Ivan

**Comment by rockmeup** [comment]
After retrying in Vmware

![Screenshot from 2019-04-10 09-34-48](https://user-images.githubusercontent.com/38371598/55850900-ffa6d100-5b73-11e9-9ce8-e7bd9e52da51.png)
================================================================================

After retrying in Virtualbox 

Failed to import appliance /root/Downloads/hl/hl-livecd.ova.

Result Code: NS_ERROR_INVALID_ARG (0x80070057)

=================================================================================

Even the ISO file did not worked

![Screenshot from 2019-04-10 09-40-09](https://user-images.githubusercontent.com/38371598/55851069-c02cb480-5b74-11e9-8178-68d777acb9ec.png)

=================================================================================
