### ISSUE TITLE
Both OVA and ISO Failure

### ISSUE THREAD

**Issue by rockmeup** [ibuetler/e1pub#4]
After retrying in Vmware

![Screenshot from 2019-04-10 09-34-48](https://user-images.githubusercontent.com/38371598/55850900-ffa6d100-5b73-11e9-9ce8-e7bd9e52da51.png)
================================================================================

After retrying in Virtualbox 

Failed to import appliance /root/Downloads/hl/hl-livecd.ova.

Result Code: NS_ERROR_INVALID_ARG (0x80070057)

=================================================================================

Even the ISO file did not worked

![Screenshot from 2019-04-10 09-40-09](https://user-images.githubusercontent.com/38371598/55851069-c02cb480-5b74-11e9-8178-68d777acb9ec.png)

=================================================================================

_Originally posted by @rockmeup in https://github.com/ibuetler/e1pub/issues/3#issuecomment-481525880_

**Comment by ibuetler** [comment]
Can't reproduce your problem. Tested the latest OVA in Windows, Linux, OSX and worked like charm. 
Please get OVA from here https://livecd.hacking-lab.com/largefiles/livecd/daily/ and tell me what OVA version and what OS you are using. 

Thank you
Ivan

**Comment by rockmeup** [comment]
Am using Kali linux 4.19.0 
I Downloaded Both OVA and ISO from here https://livecd.hacking-lab.com/largefiles/livecd/daily/ only 

Instead of Giving OVA or ISO you can  Provide VMDK's or VHD

**Comment by ibuetler** [comment]
The OVA is a "ZIP" file. Please unzip the OVA and you will find the files you are looking for. Thank you for letting me know what Host OS you are using. We can now reproduce your problem. What is the md5sum or your OVA file? I want to check what version you have used. 

Thank you 
Ivan

**Comment by rockmeup** [comment]
> The OVA is a "ZIP" file. Please unzip the OVA and you will find the files you are looking for. Thank you for letting me know what Host OS you are using. We can now reproduce your problem. What is the md5sum or your OVA file? I want to check what version you have used.
> 
> Thank you
> Ivan

Even when i unzipped it shows the same , And also I tried in windows 10 (Vmware)same Occurs

 

I used this link to download [ https://livecd.hacking-lab.com/largefiles/livecd/daily/hl-livecd.ova ]

**Comment by ibuetler** [comment]
Sorry for the inconvenience. But we double checked the import of the OVA into VirtualBox and we cannot reproduce your problem. If you want to test on your own, please get the OVA from the following URL and let me know what exact OVA version you have used. 

https://livecd.hacking-lab.com/largefiles/livecd/daily/

**Comment by ibuetler** [comment]
Get the OVA with the most recent date, thus we know what version you are using
